apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bywaymap-pvc
  namespace: office
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bywaymap-local-storage
  resources:
    requests:
      storage: 30Gi
  volumeName: bywaymap-pv
